### ISSUE TITLE
comments for even-faster-bash-startup

### ISSUE THREAD

**Issue by liskin** [liskin/work.lisk.in#8]

**Comment by colindean** [comment]
Thanks for sharing this. This inspired me to revisit my own (hastily assembled) bash loading mechanisms and [insert your timing methods into it](https://github.com/colindean/hejmo/commit/02f9df4e7a3d0ced0fc3b3891536146a63446a92#diff-d2c776a26547804849a6d55c5707aa5ceaf2c25a2d462d8527bceba0438676f6).

It helped me isolate some of the slow-loading scripts. Through this analysis, I was able to narrow down slow performers and implement [a simple caching mechanism for `brew --prefix` that yielded a 10x faster shell load](https://github.com/colindean/hejmo/commit/3d4da516feeeec9d8e806314c1201364172a5518).

**Comment by brianwood433** [comment]
I think it is a very informative article. I work at an educational company that provides students with 
<a href="https://essaysprofessor.com/nursing-essay-writing-service.html">professor essay writing</a> services around the globe. Visit it to know more.

**Comment by fionamoon233** [comment]
I think it is a very informative article. I work at an educational company that provides students with
<a href="https://essaysprofessor.com/nursing-essay-writing-service.html">professor essay writing</a> services around the globe. Visit it to know more.
