### ISSUE TITLE
[Question] linux-media-control: details about bluez -> uinput redirection

### ISSUE THREAD

**Issue by PRESFIL** [liskin/work.lisk.in#9]
Thank you for this [post][post]. I also noticed oddities when I launched
several MPRIS clients (players) in one session, and it was a fluke to find this
post! I am not the only one who noticed this.

But it does not describe how the Bluetooth headset itself is tied. I tried
searching in dotfiles but with no success. Could you provide a link to the
required commits (and, if possible, supplement the post)?

[post]: https://work.lisk.in/2020/05/06/linux-media-control.html

**Comment by liskin** [comment]
What about the Bluetooth headset? Not entirely sure what you're asking about. The post links to the key bindings for volume and there's also a link somewhere down in the Android section to the liskin-media script that does the volume control (which will become unnecessary with pulseaudio 15 though). Everything else related to the Bluetooth headset is just the default bluez/pulseaudio stuff that happens to just work. What did I miss?

**Comment by PRESFIL** [comment]
Do you use <kbd>play</kbd>/<kbd>pause</kbd>, <kbd>next</kbd>/<kbd>prev</kbd>?
If not, then I was mistaken, because it is the playback control that interests me.

> ...(and thus also headphone buttons via uinput and bluetoothd)...

It seemed to me that by this you said that you **intercept the events from the
headset keys, and broadcast them to the media-head of the keyboard playback
control**.

I am currently using [mpris-proxy][awiki] from bluez to intercept these keys.
It sends events to the MPRIS bus. But, it doesn't work well with multiple
players. It just **doesn't let go of the first player he comes across**. So I
thought you did something that I didn't succeed.

p.s. Perhaps this is mpris-proxy with [bugs][bugs], it is quite straightforward.

[awiki]: https://wiki.archlinux.org/title/MPRIS#Bluetooth
[bugs]: https://github.com/progwolff/moc-mpris/issues/5

**Comment by liskin** [comment]
I do use those, but my headset doesn't need mpris-proxy, it just generates key presses (through pulseaudio and uinput, as the blog post says) which are bound in xmonad.

**Comment by PRESFIL** [comment]
I never thought that it generates keystrokes on the keyboard (if I understood everything correctly :keyboard: )...

**Comment by PRESFIL** [comment]
OK, now everything is clear. I checked with `xev` - `uinput` does indeed send
keystrokes on the keyboard when i press the playback keys on the headset. And
prescribing hotkey bindings in wm (`xmonad`) does the trick, as you said in the
post.

Thanks for pointing this out. It was very unclear.

**Comment by liskin** [comment]
I tried to clarify this a bit in the blogpost: https://github.com/liskin/work.lisk.in/commit/98e067568298d01b4f6bc075651d581d3f904aa1
As the post is primarily about something else, I had to keep it short. It would be nice to add a section about mpris-proxy and those mediaplayer bluez APIs and so on, but I have no idea what that is about and don't really have time to dig deep into it.

**Comment by PRESFIL** [comment]
Oh, it's good.

About mpris-proxy: I have been using it for over a year, I think this is the
only alternative. But using the window manager + `playerctl` looks more
promising.

You can link to [ArchWiki][1]. Everything is already written there, and I did
exactly the same as they have written.

ArhcWiki says `mpris-proxy` is an *option for problematic headsets*, but as it
turns out, my headset is still good. So I can't say anything about this option.
But *`mpris-proxy` cannot switch to newly apeared MPRIS-player* until current
player turns off ([as I already said][2]). Therefore, I like your version better. :+1:

p.s. Interestingly, it turns out that somewhere in KDE there are the same
hotkeys inside KWin :smile: ? Although most likely there is some kind of
separate process, but I have not seen it before.

[1]: https://wiki.archlinux.org/title/MPRIS
[2]: https://github.com/liskin/work.lisk.in/issues/9#issuecomment-860172320

**Comment by liskin** [comment]
> You can link to [ArchWiki](https://wiki.archlinux.org/title/MPRIS). Everything is already written there, and I did
> exactly the same as they have written.

Actually, nothing is really explained there. What is `org.bluez.MediaPlayer1`? Why is it needed? When is it needed? What sort of headsets need it? How do you identify a headset that needs it before you buy it? What other uses does it have? None of these questions are answered there, so I can't link to it in good faith, because I want to give these answers to readers of my blog.
